title: Alan Zanão
email: alan.zanao@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Aprendizado de cada dia, histórias, soluções de problemas, pensamentos, valem a pena serem compartilhados. 
  Sou Alan, estudante de Engenharia Elétrica, cada dia buscando novos conhecimentos. Entrei na Academia pelo
  interesse em elétrons e ondas de rádio, peguei o gosto por automação e controle de sistemas, estudei línguas 
  e recentemente caminho pelo Aprendizado de Máquinas e analisando, os agora mais valiosos do que nunca, dados!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social Profiles
twitter_username:  alanzdp
github_username:   alanzanao
facebook_username: alanzdp

# Build settings
highlighter: 	   rouge
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
