title: Alan Zanão
email: alan.zanao@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Aprendizado de cada dia, histórias, soluções de problemas, pensamentos, valem a pena serem compartilhados. 
  Sou Alan, estudante de Engenharia Elétrica, cada dia buscando novos conhecimentos. Entrei na Academia pelo
  integrante, peguei o gosto por automação e controlar sistemas, estudei línguas e recentemente ando pelo caminho
  do aprendizado de máquinas e análise dos valiosos dados. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social Profiles
twitter_username:  alanzdp
github_username:   alanzanao
facebook_username: alanzdp

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
